openapi: 3.0.0
info:
  title: My Express API
  version: "1.0.0"
  description: API documentation using YAML
servers:
  - url: http://localhost:8080/api/v1

paths:
  /user/register:
    post:
      summary: Register a new user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - phone_number
                - password
                - pin
              properties:
                name:
                  type: string
                  example: John Doe
                phone_number:
                  type: string
                  example: 628123456789
                password:
                  type: string
                  example: mySecretPassword
                pin:
                  type: string
                  example: "123456"
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Validation error

  /user/login:
    post:
      summary: Login user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phone_number
                - password
              properties:
                phone_number:
                  type: string
                  example: 628123456789
                password:
                  type: string
                  example: mySecretPassword
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Invalid credentials

  /user/me:
    get:
      summary: Get user profile
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile data
        '401':
          description: Unauthorized

  /pocket:
    get:
      summary: Get all pockets for the authenticated user
      tags:
        - Pocket
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of user pockets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pocket'
        '401':
          description: Unauthorized

  /pocket/create:
    post:
      summary: Create a new pocket
      tags:
        - Pocket
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - type
                - target_nominal
              properties:
                name:
                  type: string
                  example: "Holiday Fund"
                type:
                  type: string
                  example: "saving"
                target_nominal:
                  type: number
                  example: 1000000
                deadline:
                  type: string
                  format: date
                  example: "2025-12-31"
                status:
                  type: string
                  example: "active"
                icon_name:
                  type: string
                  example: "beach"
                color_hex:
                  type: string
                  example: "#FF5733"
      responses:
        '201':
          description: Pocket created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pocket'
        '400':
          description: Bad request
        '401':
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Pocket:
      type: object
      properties:
        pocket_id:
          type: integer
          example: 1
        name:
          type: string
          example: "Holiday Fund"
        type:
          type: string
          example: "saving"
        target_nominal:
          type: number
          example: 1000000
        current_balance:
          type: number
          example: 1000000
        deadline:
          type: string
          format: date
          example: "2025-12-31"
        status:
          type: string
          example: "active"
        icon_name:
          type: string
          example: "beach"
        color_hex:
          type: string
          example: "#FF5733"
        account_number:
          type: string
          example: "1234567890"
        owner_user_id:
          type: integer
          example: 1
